name: Build and Release Resource Pack

on:
  push:
    tags:
      - 'v2.8.X/v*'

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      main_zip: ${{ steps.main_zip.outputs.zip_name }}
      modernity_zip: ${{ steps.modernity_zip.outputs.zip_name }}
      pack_version: ${{ steps.extract_version.outputs.pack_version }}
      tag_name: ${{ steps.extract_version.outputs.tag_name }}

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          ref: main
          fetch-depth: 0

      - name: Extract tag and pack version
        id: extract_version
        run: |
          TAG="${GITHUB_REF##*/}"
          PACK_VERSION="${TAG#v2.8.X/}"
          echo "::set-output name=pack_version::$PACK_VERSION"
          echo "::set-output name=tag_name::$TAG"

      - name: Install tools
        run: sudo apt-get update && sudo apt-get install -y jq zip

      - name: Build ZIP for main
        id: main_zip
        run: |
          DESC="§8GTNH v2.8.X §f/ §3Pack ${{ steps.extract_version.outputs.pack_version }}"
          jq --arg desc "$DESC" '.pack.description = $desc' pack.mcmeta > temp.mcmeta && mv temp.mcmeta pack.mcmeta
          ZIP_NAME="Shadow UI ${{ steps.extract_version.outputs.pack_version }}.zip"
          zip -r "$ZIP_NAME" assets pack.mcmeta pack.png README.md
          echo "::set-output name=zip_name::$ZIP_NAME"

      - name: Checkout modernity branch
        uses: actions/checkout@v3
        with:
          ref: modernity
          fetch-depth: 0

      - name: Build ZIP for modernity
        id: modernity_zip
        run: |
          DESC="§8GTNH v2.8.X §f/ §3Pack ${{ steps.extract_version.outputs.pack_version }} §f- §2Modernity version"
          jq --arg desc "$DESC" '.pack.description = $desc' pack.mcmeta > temp.mcmeta && mv temp.mcmeta pack.mcmeta
          ZIP_NAME="Shadow UI ${{ steps.extract_version.outputs.pack_version }} - Modernity version.zip"
          zip -r "$ZIP_NAME" assets pack.mcmeta pack.png README.md
          echo "::set-output name=zip_name::$ZIP_NAME"

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Upload release assets
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ needs.build.outputs.tag_name }}
          name: ${{ needs.build.outputs.tag_name }}
          body: |
            ### Version
            - Minecraft 1.7.10
            - GTNH 2.8.X
            - Pack version ${{ needs.build.outputs.pack_version }}
          files: |
            ${{ needs.build.outputs.main_zip }}
            ${{ needs.build.outputs.modernity_zip }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}