name: Build and Release Resource Pack

on:
  push:
    tags:
      - 'v2.8.X/v*'  # Trigger on tags like v2.8.X/v4.2

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      main_zip: ${{ steps.main_zip.outputs.zip_name }}
      modernity_zip: ${{ steps.modernity_zip.outputs.zip_name }}

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          ref: main
          fetch-depth: 0

      - name: Extract version from tag
        id: vars
        run: |
          TAG="${GITHUB_REF##*/}"
          echo "PACK_VERSION=${TAG#v2.8.X/}" >> $GITHUB_ENV
          echo "TAG=$TAG" >> $GITHUB_ENV

      - name: Install tools
        run: sudo apt-get update && sudo apt-get install -y jq zip

      - name: Build ZIP for main
        id: main_zip
        run: |
          DESC="§8GTNH v2.8.X §f/ §3Pack $PACK_VERSION"
          jq --arg desc "$DESC" '.pack.description = $desc' pack.mcmeta > temp.mcmeta && mv temp.mcmeta pack.mcmeta
          ZIP_NAME="Shadow UI $PACK_VERSION.zip"
          zip -r "$ZIP_NAME" assets pack.mcmeta pack.png README.md
          echo "zip_name=$ZIP_NAME" >> $GITHUB_OUTPUT

      - name: Checkout modernity branch
        uses: actions/checkout@v3
        with:
          ref: modernity
          fetch-depth: 0

      - name: Build ZIP for modernity
        id: modernity_zip
        run: |
          DESC="§8GTNH v2.8.X §f/ §3Pack $PACK_VERSION §f- §2Modernity version"
          jq --arg desc "$DESC" '.pack.description = $desc' pack.mcmeta > temp.mcmeta && mv temp.mcmeta pack.mcmeta
          ZIP_NAME="Shadow UI $PACK_VERSION - Modernity version.zip"
          zip -r "$ZIP_NAME" assets pack.mcmeta pack.png README.md
          echo "zip_name=$ZIP_NAME" >> $GITHUB_OUTPUT

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Create GitHub Release and upload assets
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.TAG }}
          name: ${{ env.TAG }}
          body: |
            ### Version
            - Minecraft 1.7.10
            - GTNH 2.8.X
            - Pack version ${{ env.PACK_VERSION }}
          files: |
            ${{ needs.build.outputs.main_zip }}
            ${{ needs.build.outputs.modernity_zip }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG: ${{ github.ref_name }}
          PACK_VERSION: ${{ github.ref_name && github.ref_name.replace('v2.8.X/', '') }}
